// Mock data con branchId incluido - Sistema Multi-Sucursal

export const mockOrdersWithBranches = [
  {
    id: "OT-001",
    branchId: "branch-1",
    branchName: "Sucursal Centro",
    vehicleId: "ABC-123",
    clientId: "client-1",
    vehicle: "Toyota Corolla 2020",
    client: "Juan Pérez",
    service: "Cambio de aceite + Filtros",
    status: "in-progress",
    date: "2024-12-10",
    estimatedCost: 45000,
    parts: [
      { name: "Aceite sintético 5W-30", quantity: 4, price: 8000 },
      { name: "Filtro de aceite", quantity: 1, price: 5000 },
    ],
  },
  {
    id: "OT-002",
    branchId: "branch-2",
    branchName: "Sucursal Providencia",
    vehicleId: "XYZ-789",
    clientId: "client-2",
    vehicle: "Honda Civic 2019",
    client: "María González",
    service: "Revisión de frenos",
    status: "pending",
    date: "2024-12-11",
    estimatedCost: 120000,
    parts: [
      { name: "Pastillas de freno delanteras", quantity: 4, price: 35000 },
      { name: "Discos de freno", quantity: 2, price: 70000 },
    ],
  },
  {
    id: "OT-003",
    branchId: "branch-1",
    branchName: "Sucursal Centro",
    vehicleId: "DEF-456",
    clientId: "client-3",
    vehicle: "Hyundai Accent 2021",
    client: "Pedro Muñoz",
    service: "Cambio de batería",
    status: "completed",
    date: "2024-12-09",
    estimatedCost: 85000,
    parts: [{ name: "Batería 12V 60Ah", quantity: 1, price: 80000 }],
  },
  {
    id: "OT-004",
    branchId: "branch-3",
    branchName: "Sucursal Las Condes",
    vehicleId: "GHI-789",
    clientId: "client-4",
    vehicle: "Nissan Sentra 2022",
    client: "Ana López",
    service: "Mantención 10.000 km",
    status: "in-progress",
    date: "2024-12-12",
    estimatedCost: 95000,
    parts: [
      { name: "Aceite sintético", quantity: 4, price: 8000 },
      { name: "Filtro aire", quantity: 1, price: 12000 },
      { name: "Filtro combustible", quantity: 1, price: 15000 },
    ],
  },
  {
    id: "OT-005",
    branchId: "branch-2",
    branchName: "Sucursal Providencia",
    vehicleId: "JKL-456",
    clientId: "client-5",
    vehicle: "Kia Rio 2021",
    client: "Carlos Ramírez",
    service: "Cambio de correa distribución",
    status: "in-progress",
    date: "2024-12-12",
    estimatedCost: 180000,
    parts: [
      { name: "Kit correa distribución", quantity: 1, price: 120000 },
      { name: "Bomba de agua", quantity: 1, price: 45000 },
    ],
  },
  {
    id: "OT-006",
    branchId: "branch-1",
    branchName: "Sucursal Centro",
    vehicleId: "MNO-789",
    clientId: "client-6",
    vehicle: "Chevrolet Spark 2019",
    client: "Laura Torres",
    service: "Cambio de neumáticos",
    status: "completed",
    date: "2024-12-11",
    estimatedCost: 240000,
    parts: [
      { name: "Neumático 175/65R14", quantity: 4, price: 55000 },
    ],
  },
  {
    id: "OT-007",
    branchId: "branch-3",
    branchName: "Sucursal Las Condes",
    vehicleId: "PQR-123",
    clientId: "client-7",
    vehicle: "Mazda 3 2022",
    client: "Diego Fernández",
    service: "Escaneo + Diagnóstico",
    status: "pending",
    date: "2024-12-13",
    estimatedCost: 25000,
    parts: [],
  },
  {
    id: "OT-008",
    branchId: "branch-2",
    branchName: "Sucursal Providencia",
    vehicleId: "STU-456",
    clientId: "client-8",
    vehicle: "Suzuki Swift 2020",
    client: "Valentina Soto",
    service: "Cambio pastillas + discos freno",
    status: "in-progress",
    date: "2024-12-12",
    estimatedCost: 150000,
    parts: [
      { name: "Pastillas delanteras", quantity: 4, price: 35000 },
      { name: "Discos delanteros", quantity: 2, price: 70000 },
    ],
  },
]

export const mockInventoryWithBranches = [
  // Sucursal Centro
  {
    id: "inv-1",
    branchId: "branch-1",
    branchName: "Sucursal Centro",
    code: "AC-5W30-001",
    name: "Aceite sintético 5W-30",
    category: "Lubricantes",
    stock: 24,
    minStock: 10,
    price: 8000,
    supplier: "Shell",
  },
  {
    id: "inv-2",
    branchId: "branch-1",
    branchName: "Sucursal Centro",
    code: "FLT-001",
    name: "Filtro de aceite universal",
    category: "Filtros",
    stock: 15,
    minStock: 8,
    price: 5000,
    supplier: "Mann Filter",
  },
  {
    id: "inv-7",
    branchId: "branch-1",
    branchName: "Sucursal Centro",
    code: "AC-10W40-001",
    name: "Aceite semi-sintético 10W-40",
    category: "Lubricantes",
    stock: 18,
    minStock: 12,
    price: 6500,
    supplier: "Castrol",
  },
  {
    id: "inv-8",
    branchId: "branch-1",
    branchName: "Sucursal Centro",
    code: "BAT-12V-002",
    name: "Batería 12V 45Ah",
    category: "Baterías",
    stock: 3,
    minStock: 5,
    price: 65000,
    supplier: "Bosch",
  },
  {
    id: "inv-9",
    branchId: "branch-1",
    branchName: "Sucursal Centro",
    code: "NEUM-175-001",
    name: "Neumático 175/65R14",
    category: "Neumáticos",
    stock: 16,
    minStock: 8,
    price: 55000,
    supplier: "Michelin",
  },
  
  // Sucursal Providencia
  {
    id: "inv-3",
    branchId: "branch-2",
    branchName: "Sucursal Providencia",
    code: "PAD-FRN-001",
    name: "Pastillas de freno delanteras",
    category: "Frenos",
    stock: 8,
    minStock: 5,
    price: 35000,
    supplier: "Brembo",
  },
  {
    id: "inv-4",
    branchId: "branch-2",
    branchName: "Sucursal Providencia",
    code: "DSC-FRN-001",
    name: "Discos de freno",
    category: "Frenos",
    stock: 6,
    minStock: 4,
    price: 70000,
    supplier: "Brembo",
  },
  {
    id: "inv-10",
    branchId: "branch-2",
    branchName: "Sucursal Providencia",
    code: "AC-5W30-002",
    name: "Aceite sintético 5W-30",
    category: "Lubricantes",
    stock: 20,
    minStock: 10,
    price: 8000,
    supplier: "Shell",
  },
  {
    id: "inv-11",
    branchId: "branch-2",
    branchName: "Sucursal Providencia",
    code: "KIT-DIST-001",
    name: "Kit correa de distribución",
    category: "Correas",
    stock: 4,
    minStock: 3,
    price: 120000,
    supplier: "Gates",
  },
  {
    id: "inv-12",
    branchId: "branch-2",
    branchName: "Sucursal Providencia",
    code: "BOMB-AGU-001",
    name: "Bomba de agua",
    category: "Refrigeración",
    stock: 2,
    minStock: 4,
    price: 45000,
    supplier: "Gates",
  },
  
  // Sucursal Las Condes
  {
    id: "inv-5",
    branchId: "branch-3",
    branchName: "Sucursal Las Condes",
    code: "BAT-12V-001",
    name: "Batería 12V 60Ah",
    category: "Baterías",
    stock: 8,
    minStock: 3,
    price: 80000,
    supplier: "Bosch",
  },
  {
    id: "inv-6",
    branchId: "branch-3",
    branchName: "Sucursal Las Condes",
    code: "FLT-AIR-001",
    name: "Filtro de aire",
    category: "Filtros",
    stock: 12,
    minStock: 6,
    price: 12000,
    supplier: "Mann Filter",
  },
  {
    id: "inv-13",
    branchId: "branch-3",
    branchName: "Sucursal Las Condes",
    code: "FLT-COMB-001",
    name: "Filtro de combustible",
    category: "Filtros",
    stock: 10,
    minStock: 5,
    price: 15000,
    supplier: "Mann Filter",
  },
  {
    id: "inv-14",
    branchId: "branch-3",
    branchName: "Sucursal Las Condes",
    code: "AC-10W40-002",
    name: "Aceite semi-sintético 10W-40",
    category: "Lubricantes",
    stock: 22,
    minStock: 12,
    price: 6500,
    supplier: "Castrol",
  },
  {
    id: "inv-15",
    branchId: "branch-3",
    branchName: "Sucursal Las Condes",
    code: "NEUM-185-001",
    name: "Neumático 185/60R15",
    category: "Neumáticos",
    stock: 12,
    minStock: 8,
    price: 62000,
    supplier: "Bridgestone",
  },
]

export const mockAppointmentsWithBranches = [
  {
    id: "apt-1",
    branchId: "branch-1",
    branchName: "Sucursal Centro",
    clientName: "Roberto Silva",
    vehicle: "Mazda 3 2021",
    service: "Cambio de aceite",
    date: "2024-12-13",
    time: "09:00",
    status: "confirmed",
  },
  {
    id: "apt-2",
    branchId: "branch-2",
    branchName: "Sucursal Providencia",
    clientName: "Laura Martínez",
    vehicle: "Suzuki Swift 2020",
    service: "Revisión general",
    date: "2024-12-13",
    time: "10:30",
    status: "pending",
  },
  {
    id: "apt-3",
    branchId: "branch-3",
    branchName: "Sucursal Las Condes",
    clientName: "Diego Torres",
    vehicle: "Kia Rio 2022",
    service: "Diagnóstico computacional",
    date: "2024-12-13",
    time: "14:00",
    status: "confirmed",
  },
  {
    id: "apt-4",
    branchId: "branch-1",
    branchName: "Sucursal Centro",
    clientName: "Sofía Ramírez",
    vehicle: "Chevrolet Spark 2019",
    service: "Cambio de frenos",
    date: "2024-12-14",
    time: "11:00",
    status: "pending",
  },
  {
    id: "apt-5",
    branchId: "branch-2",
    branchName: "Sucursal Providencia",
    clientName: "Andrés Morales",
    vehicle: "Nissan Versa 2021",
    service: "Mantención 15.000 km",
    date: "2024-12-13",
    time: "15:30",
    status: "confirmed",
  },
  {
    id: "apt-6",
    branchId: "branch-3",
    branchName: "Sucursal Las Condes",
    clientName: "Camila Vargas",
    vehicle: "Toyota Yaris 2020",
    service: "Cambio de batería",
    date: "2024-12-14",
    time: "09:30",
    status: "confirmed",
  },
  {
    id: "apt-7",
    branchId: "branch-1",
    branchName: "Sucursal Centro",
    clientName: "Felipe Castro",
    vehicle: "Hyundai i10 2022",
    service: "Alineación y balanceo",
    date: "2024-12-14",
    time: "13:00",
    status: "pending",
  },
  {
    id: "apt-8",
    branchId: "branch-2",
    branchName: "Sucursal Providencia",
    clientName: "Javiera Rojas",
    vehicle: "Honda Fit 2019",
    service: "Cambio pastillas de freno",
    date: "2024-12-14",
    time: "16:00",
    status: "confirmed",
  },
]

// Resumen por sucursal para demostración
export const branchSummary = {
  "branch-1": {
    name: "Sucursal Centro",
    code: "SUC-001",
    activeOrders: 3,
    todayAppointments: 2,
    lowStockItems: 1,
    totalRevenue: 370000,
  },
  "branch-2": {
    name: "Sucursal Providencia",
    code: "SUC-002",
    activeOrders: 3,
    todayAppointments: 2,
    lowStockItems: 1,
    totalRevenue: 270000,
  },
  "branch-3": {
    name: "Sucursal Las Condes",
    code: "SUC-003",
    activeOrders: 2,
    todayAppointments: 2,
    lowStockItems: 0,
    totalRevenue: 95000,
  },
}
